name: CI

env:
  CI: true
  FOUNDRY_PROFILE: 'intense'

on:
  push:
    branches:
      - master
  pull_request:
    branches: ['*', '**/*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-solidity-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-solidity-utils test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-solidity-utils test-fuzz

  test-standalone-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-standalone-utils test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-standalone-utils test-fuzz

  test-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-vault test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-vault test-fuzz

  test-pool-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-pool-utils test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-pool-utils test-fuzz

  test-pool-weighted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-pool-weighted test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-pool-weighted test-fuzz

  test-pool-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-pool-stable test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-pool-stable test-fuzz

  test-pool-linear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-pool-linear test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-pool-linear test-fuzz

  test-liquidity-mining:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-liquidity-mining test
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: yarn workspace @balancer-labs/v2-liquidity-mining test-fuzz

  test-governance-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-governance-scripts test

  test-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build Balancer JS
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Compile
        run: yarn build # Ideally we wouldn't depend on the packages of other artifacts, but we use some of their mocks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Forked Network Cache
        # Hardhat caches node requests when working with forked networks (e.g. when querying contract code, storage,
        # etc.) to save time in future runs. We cache this directory accross runs.
        # This cache action is special for a couple reasons, which originate from a) it not occupying much disk size,
        # and b) the cache never being invalid (as past blockchain data is immutable). We therefore:
        #  - save the cache even on action failure (which may be caused due to a timeout), even if this could result in
        #    some wasted space. For this we use the always-upload-cache fork of the basic action.
        #  - use a different key on every single run, causing for the cache to always be saved.
        #  - use a wildcard as a restore key, which will cause all stored keys to match and the most recent one to be
        #    selected.
        uses: pat-s/always-upload-cache@v3.0.1
        id: cache-forked-network
        with:
          path: 'pkg/deployments/cache/hardhat-network-fork/**'
          key: hardhat-network-fork-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            hardhat-network-fork-
      - name: Prepare Config
        run: yarn workspace @balancer-labs/v2-deployments ci:prepare-config
        env:
          MAINNET_RPC_ENDPOINT: ${{ secrets.ALCHEMY_MAINNET_ARCHIVE_ENDPOINT }}
          POLYGON_RPC_ENDPOINT: ${{ secrets.ALCHEMY_POLYGON_ARCHIVE_ENDPOINT }}
          ARBITRUM_RPC_ENDPOINT: ${{ secrets.ALCHEMY_ARBITRUM_ARCHIVE_ENDPOINT }}
          OPTIMISM_RPC_ENDPOINT: ${{ secrets.ALCHEMY_OPTIMISM_ARCHIVE_ENDPOINT }}
      - name: Test
        run: yarn workspace @balancer-labs/v2-deployments test
